replicaCount: 1

image:
  repository: ghcr.io/seung-ju-org/portfolio
  pullPolicy: IfNotPresent
  tag: "main-72-c7fb7b8"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-route53"
  hosts:
    - host: portfolio.seung-ju.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: portfolio-seungju-tls
      hosts:
        - portfolio.seung-ju.com

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 20
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

nodeSelector: {}
tolerations: []
affinity: {}

env:
  NODE_ENV: production
  NEXT_PUBLIC_SITE_URL: "https://portfolio.seung-ju.com"
  REDIS_HOST: "redis-master.redis.svc"
  REDIS_PORT: "6379"

secretEnv:
  DATABASE_URL: "postgresql://<username>:<password>@postgresql-primary.postgresql.svc:5432/<database>?schema=portfolio"
  REDIS_PASSWORD: "<redis-password>"
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  SMTP_USER: "smtp-user@example.com"
  SMTP_PASS: "<smtp-password>"
  SMTP_DOMAIN: "portfolio.seung-ju.com"
  SMTP_PROTOCOL: "tls"
  CONTACT_TO_EMAIL: "seung-ju@seung-ju.com"
  CONTACT_FROM_EMAIL: "no-reply@portfolio.seung-ju.com"
