apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio.fullname" . }}
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portfolio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portfolio.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portfolio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: DATABASE_URL
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: REDIS_PASSWORD
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_PORT
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_USER
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_PASS
            - name: SMTP_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_DOMAIN
            - name: SMTP_PROTOCOL
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: SMTP_PROTOCOL
            - name: CONTACT_TO_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: CONTACT_TO_EMAIL
            - name: CONTACT_FROM_EMAIL
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio.fullname" . }}-env
                  key: CONTACT_FROM_EMAIL
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
