apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio.fullname" . }}-env
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secretEnv.DATABASE_URL is required" .Values.secretEnv.DATABASE_URL | quote }}
  REDIS_PASSWORD: {{ .Values.secretEnv.REDIS_PASSWORD | quote }}
  SENTRY_DSN: {{ required "secretEnv.SENTRY_DSN is required" .Values.secretEnv.SENTRY_DSN | quote }}
  NEXT_PUBLIC_SENTRY_DSN: {{ default .Values.secretEnv.SENTRY_DSN .Values.secretEnv.NEXT_PUBLIC_SENTRY_DSN | quote }}
